//
//  HomeViewController.swift
//  Recody
//
//  Created by 마경미 on 2022/08/04.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class HomeViewController: UIViewController {
    var viewModel = HomeViewModel()

    @IBOutlet weak var workScrollView: UIScrollView!
    @IBOutlet weak var workStackView: UIStackView!
    @IBOutlet weak var notificationButton: UIButton!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setUp()
        setWorkView()
    }

    static func getInstanse() -> HomeViewController {
        guard let vc =  UIStoryboard(name: "Home", bundle: nil).instantiateViewController(withIdentifier: "home") as? HomeViewController
        else {
            fatalError()
        }
        return vc
    }

    func setUp() {
//        self.interactor?.just(UseCase.setting).drop()
        self.notificationButton.addGestureRecognizer(UITapGestureRecognizer(target: self, action: #selector(clickEvent)))
    }
    
    func setWorkView() {
        for work in viewModel.works {
            let view = WorkView()
            view.setView(work: work)
            view.tag = 109
            view.addGestureRecognizer(UITapGestureRecognizer(target: self, action: #selector(clickEvent(_:))))
            workStackView.addArrangedSubview(view)
        }
    }

    @objc func clickEvent(_ sender: UITapGestureRecognizer) {
        if let tag = sender.view?.tag {
            guard let useCase = UseCase(rawValue: tag) else { return }
            switch useCase {
            case .setting:
                ServiceProvider.shaerd.apiService.send(.getUserInfomation)
                ServiceProvider.shaerd.apiService.send(.getMyRecentContinuingRecord)
                ServiceProvider.shaerd.apiService.send(.getMovies)
            break
            case .pushWorkDetailInfo:
                self.navigationController?.pushViewController(WorkDetailInfoViewController.getInstanse(), animated: true)
            case .pushNotification:
                self.navigationController?.pushViewController(NotificationViewController.getInstanse(), animated: true)
            default:
                break
            }
        }
    }

    enum UseCase: Int {
        case setting = 105
        case notification = 106
        case moveReviewing = 107
        case workCategory = 108
        case pushWorkDetailInfo = 109
        case pushNotification = 110
        var number: Int {
            return self.rawValue
        }
    }
//    override func displaySuccess(orderNumber: Int, dataStore: DataStoreType?) {
//        guard let useCase = UseCase(rawValue: orderNumber) else { return }
//        switch useCase {
//        case .setting:
//            if let data = dataStore?.data(useCase)?.fetch(UserDataModel.self) {
//                let temp = data.data["signInInfo"] as? [String: String]
//                guard let accessToken = temp?["accessToken"] else { return }
//                guard let refreshToken = temp?["refreshToken"] else { return }
//                KeyChain.create(key: "accessToken", token: accessToken)
//                KeyChain.create(key: "refreshToken", token: refreshToken)
//                print("요깅깅교익요긱")
//                print(data)
//            }
//        default:
//            self.presenter?.alertService.showToast("\(useCase)")
//        }
//    }
}
