//
//  WorkDetailInfoViewController.swift
//  Recody
//
//  Created by 마경미 on 2022/08/23.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class WorkDetailInfoViewController: CommonVC {
    var viewModel = WorkDetailInfoViewModel()
    
    let works: [Work] = [
        Work(id: "1", name: "WANDAVISION", image: "wanda"),
        Work(id: "2", name: "NOWAYHOME", image: "spiderman")
    ]
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    // UseCase 정리
    // 1. 이전화면
    // 2. 작품 선택
    // 3. 좋아요 누르기
    // 4. 감상평 추가하기 버튼
    enum UseCase: Int, OrderType {
        case setting = 100
        case back = 101
        case moveWork = 102
        case dibs = 103
        case addReview = 104
        var number: Int {
            return self.rawValue
        }
    }
    
    override func display(orderNumber: Int) {
        guard let useCase = UseCase(rawValue: orderNumber) else { return }
//        switch useCase {
//        case .setting:
//            self
//        }
    }
    
    override func displayErorr(orderNumber: Int, msg: String?) {
        guard let useCase = UseCase(rawValue: orderNumber) else { return }
        switch useCase {
        default:
            self.presenter?.alertService.showToast("\(useCase)")
        }
    }
    
    override func displaySuccess(orderNumber: Int, dataStore: DataStoreType?) {
        guard let useCase = UseCase(rawValue: orderNumber) else { return }
        switch useCase {
        default:
            self.presenter?.alertService.showToast("\(useCase)")
        }
    }
    
    // clickevent 정의
    
    // setup
    
    // viewdidload
}
