//
//  WorkDetailInfoRouter.swift
//  Recody
//
//  Created by 마경미 on 2022/08/23.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol WorkDetailInfoRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol WorkDetailInfoDataPassing
{
  var dataStore: WorkDetailInfoDataStore? { get }
}

class WorkDetailInfoRouter: NSObject, WorkDetailInfoRoutingLogic, WorkDetailInfoDataPassing
{
  weak var viewController: WorkDetailInfoViewController?
  var dataStore: WorkDetailInfoDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: WorkDetailInfoViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: WorkDetailInfoDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
