//
//  WorkDetailInfoInteractor.swift
//  Recody
//
//  Created by 마경미 on 2022/08/23.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WorkDetailInfoBusinessLogic
{
  func doSomething(request: WorkDetailInfo.Something.Request)
}

protocol WorkDetailInfoDataStore
{
  //var name: String { get set }
}

class WorkDetailInfoInteractor: WorkDetailInfoBusinessLogic, WorkDetailInfoDataStore
{
  var presenter: WorkDetailInfoPresentationLogic?
  var worker: WorkDetailInfoWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: WorkDetailInfo.Something.Request)
  {
    worker = WorkDetailInfoWorker()
    worker?.doSomeWork()
    
    let response = WorkDetailInfo.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
