//
//  WorkDetailInfoRouter.swift
//  Recody
//
//  Created by 마경미 on 2022/08/23.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol WorkDetailInfoRoutingLogic {
  // func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol WorkDetailInfoDataPassing {
  var dataStore: WorkDetailInfoDataStore? { get }
}

class WorkDetailInfoRouter: NSObject, WorkDetailInfoRoutingLogic, WorkDetailInfoDataPassing {
  weak var viewController: WorkDetailInfoViewController?
  var dataStore: WorkDetailInfoDataStore?
}
