//
//  ReviewModels.swift
//  Recody
//
//  Created by 마경미 on 23.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum PreReview {
  // MARK: Use cases
    struct Data {
        let record: Record
    }

    struct Record {
        let recordCount: Int
        let recordId: String
        let userId: Int
        let contentId: String
        let note: String
        let date: Date
    }

    struct PreReview {
        let recordCount: Int
        let date: Date
        let note: String
    }

  enum API {
    struct Request {
    }
    struct Response {
        let message: String
        let data: Data
    }
    struct ViewModel {
    }
  }
}
