//
//  ModifyProfileInteractor.swift
//  Recody
//
//  Created by 마경미 on 29.10.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ModifyProfileBusinessLogic {
    func doSomething(request: ModifyProfile.Something.Request)
}

protocol ModifyProfileDataStore {
}

class ModifyProfileInteractor: ModifyProfileBusinessLogic, ModifyProfileDataStore {
    var presenter: ModifyProfilePresentationLogic?
    var worker: ModifyProfileWorker?

    // MARK: Do something

    func doSomething(request: ModifyProfile.Something.Request) {
        worker = ModifyProfileWorker()
        worker?.doSomeWork()

        let response = ModifyProfile.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
