//
//  ModifyProfilePresenter.swift
//  Recody
//
//  Created by 마경미 on 29.10.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ModifyProfilePresentationLogic {
    func presentSomething(response: ModifyProfile.Something.Response)
}

class ModifyProfilePresenter: ModifyProfilePresentationLogic {
    weak var viewController: ModifyProfileDisplayLogic?

    // MARK: Do something
    func presentSomething(response: ModifyProfile.Something.Response) {
        let viewModel = ModifyProfile.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
