//
//  EditCategoryInteractor.swift
//  Recody
//
//  Created by 마경미 on 2022/09/05.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditCategoryBusinessLogic {
  func doSomething(request: EditCategory.Something.Request)
}

protocol EditCategoryDataStore {
  // var name: String { get set }
}

class EditCategoryInteractor: EditCategoryBusinessLogic, EditCategoryDataStore {
  var presenter: EditCategoryPresentationLogic?
  var worker: EditCategoryWorker?

  func doSomething(request: EditCategory.Something.Request) {
    worker = EditCategoryWorker()
    worker?.doSomeWork()

    let response = EditCategory.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
