//
//  EditGenreInteractor.swift
//  Recody
//
//  Created by 마경미 on 2022/09/05.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditGenreBusinessLogic
{
  func doSomething(request: EditGenre.Something.Request)
}

protocol EditGenreDataStore
{
  //var name: String { get set }
}

class EditGenreInteractor: EditGenreBusinessLogic, EditGenreDataStore
{
  var presenter: EditGenrePresentationLogic?
  var worker: EditGenreWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: EditGenre.Something.Request)
  {
    worker = EditGenreWorker()
    worker?.doSomeWork()
    
    let response = EditGenre.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
