//
//  WorkDetailInfoViewController.swift
//  Recody
//
//  Created by 마경미 on 2022/08/23.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class WorkDetailInfoViewController: UIViewController {
    var viewModel = WorkDetailInfoViewModel()
    @IBOutlet weak var workListView: WorkListView!
    @IBOutlet weak var categoryButton: CategoryButton! {
        didSet {
            // api 코드 작성 한 후 useCase로 변경
            categoryButton.setButton(with: "영화")
        }
    }
    
    let works: [Work] = [
        Work(id: "1", name: "WANDAVISION", image: "wanda"),
        Work(id: "2", name: "NOWAYHOME", image: "spiderman")
    ]
    
    override func viewDidLoad() {
        super.viewDidLoad()
        workListView.setView(work: works)
    }
    static func getInstanse() -> WorkDetailInfoViewController{
        guard let vc =  UIStoryboard(name: "WorkDetailInfo", bundle: nil).instantiateViewController(withIdentifier: "workDetailInfo") as? WorkDetailInfoViewController
        else {
            fatalError()
        }
        return vc
    }
    // UseCase 정리
    // 1. 이전화면
    // 2. 작품 선택
    // 3. 좋아요 누르기
    // 4. 감상평 추가하기 버튼
    enum UseCase: Int {
        case setting = 100
        case back = 101
        case moveWork = 102
        case dibs = 103
        case addReview = 104
        var number: Int {
            return self.rawValue
        }
    }
    
    // clickevent 정의
    
    // setup
    
    // viewdidload
}
