//
//  EditCategoryRouter.swift
//  Recody
//
//  Created by 마경미 on 2022/09/05.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol EditCategoryRoutingLogic {
     func routeToEditGenre(segue: UIStoryboardSegue?)
}

protocol EditCategoryDataPassing {
    var dataStore: EditCategoryDataStore? { get }
}

class EditCategoryRouter: NSObject, EditCategoryRoutingLogic, EditCategoryDataPassing {
    weak var viewController: EditCategoryViewController?
    var dataStore: EditCategoryDataStore?

    func routeToEditGenre(segue: UIStoryboardSegue?) {
      if segue == nil {
        let storyboard = UIStoryboard(name: "EditGenre", bundle: nil)
          guard let destinationVC = storyboard.instantiateViewController(withIdentifier: "editGenre") as? EditGenreViewController else {
              return
          }
          navigateToEditGenre(source: viewController!, destination: destinationVC)
      }
    }

    func navigateToEditGenre(source: EditCategoryViewController, destination: EditGenreViewController) {
        source.navigationController?.pushViewController(destination, animated: true)
    }
}
