//
//  EditGenrePresenter.swift
//  Recody
//
//  Created by 마경미 on 2022/09/05.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditGenrePresentationLogic {
    func presentSomething(response: EditGenre.Something.Response)
}

class EditGenrePresenter: EditGenrePresentationLogic {
    weak var viewController: EditGenreDisplayLogic?

    // MARK: Do something
    func presentSomething(response: EditGenre.Something.Response) {
        let viewModel = EditGenre.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
