//
//  EditGenreViewController.swift
//  Recody
//
//  Created by 마경미 on 2022/09/05.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class EditGenreViewController: UIViewController {
    var genres = [ "로맨스 코미디", "스릴러", "액션", "범죄", "SF", "코미디", "공포", "전쟁",
                   "스포츠", "판타지", "음악", "뮤지컬", "장르", "장르", "장르", "장르", "장르", "장르", "장르", "장르"]

    @IBOutlet weak var scrollView: UIScrollView!
    @IBOutlet weak var viewHeight: NSLayoutConstraint!
    @IBOutlet weak var category: CustomCategory!

    // MARK: View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    static func getInstanse() -> EditGenreViewController{
        guard let vc =  UIStoryboard(name: "CategorySetting", bundle: nil).instantiateViewController(withIdentifier: "CategorySetting") as? EditGenreViewController
        else {
            fatalError()
        }
        return vc
    }

}
