//
//  ReviewPresenter.swift
//  Recody
//
//  Created by 마경미 on 23.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PreReviewPresentationLogic {
    func presentSomething(response: PreReview.API.Response)
}

class PreReviewPresenter: PreReviewPresentationLogic {
    weak var viewController: PreReviewDisplayLogic?

    // MARK: Do something

    func presentSomething(response: PreReview.API.Response) {
        let viewModel = PreReview.API.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)

    }
}
