//
//  ReviewRouter.swift
//  Recody
//
//  Created by 마경미 on 23.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol PreReviewRoutingLogic {
    // func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol PreReviewDataPassing {
    var dataStore: PreReviewDataStore? { get }
}

class PreReviewRouter: NSObject, PreReviewRoutingLogic, PreReviewDataPassing {
    weak var viewController: PreReviewViewController?
    var dataStore: PreReviewDataStore?

    // MARK: Routing

    // MARK: Navigation

    // func navigateToSomewhere(source: ReviewViewController, destination: SomewhereViewController)
    // {
    //  source.show(destination, sender: nil)
    // }

    // MARK: Passing data

    // func passDataToSomewhere(source: ReviewDataStore, destination: inout SomewhereDataStore) {
    //  destination.name = source.name
    // }
}
