//
//  MySearchInteractor.swift
//  Recody
//
//  Created by 마경미 on 12.10.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MySearchBusinessLogic
{
  func doSomething(request: MySearch.API.Request)
}

protocol MySearchDataStore
{
  //var name: String { get set }
}

class MySearchInteractor: MySearchBusinessLogic, MySearchDataStore
{
  var presenter: MySearchPresentationLogic?
  var worker: MySearchWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: MySearch.API.Request)
  {
    worker = MySearchWorker()
    worker?.doSomeWork()
    
    let response = MySearch.API.Response()
    presenter?.presentSomething(response: response)
  }
}
