//
//  MySearchPresenter.swift
//  Recody
//
//  Created by 마경미 on 12.10.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MySearchPresentationLogic {
    func presentSomething(response: MySearch.API.Response)
}

class MySearchPresenter: MySearchPresentationLogic {
    weak var viewController: MySearchDisplayLogic?

    // MARK: Do something

    func presentSomething(response: MySearch.API.Response) {
        let viewModel = MySearch.API.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
