//
//  HomeModels.swift
//  Recody
//
//  Created by 마경미 on 2022/08/04.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home {
    // MARK: Use cases
    enum TestCategory {
        struct Request {
        }
        struct Response {
            let categoryList: [Category]
        }
        struct ViewModel {
        }
    }

    enum TestWork {
        struct Request {
        }
        struct Response {
            let workList: [Work]
        }
        struct ViewModel {
        }
    }
}
