//
//  HomePresenter.swift
//  Recody
//
//  Created by 마경미 on 2022/08/04.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic {
  func presentCategory(response: Home.TestCategory.Response)
    func presentWork(response: Home.TestWork.Response)
}

class HomePresenter: HomePresentationLogic {
    weak var viewController: HomeDisplayLogic?

    func presentCategory(response: Home.TestCategory.Response) {
        let viewModel = Home.TestCategory.ViewModel()
        viewController?.displayTestCategory(viewModel: viewModel)
    }

    func presentWork(response: Home.TestWork.Response) {
        let viewModel = Home.TestWork.ViewModel()
        viewController?.displayTestWork(viewModel: viewModel)
    }
}
