//
//  HomeModels.swift
//  Recody
//
//  Created by 마경미 on 2022/08/04.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation
import UIKit

class HomeViewModel {
    var userName: String = ""
    var recentContinuingRecord: ContinuingRecord?
    var content: Content?
    
    init?() {
        
    }
    
    func setUserName(name: String) {
        userName = name
    }
    
    func setRecentContinuingRecord(record: ContinuingRecord) {
        recentContinuingRecord = record
    }
    
    func setContent(content: Content) {
        self.content = content
    }
}

class ContinuingRecord {
    var contentTag: String?
    var contentName: String?
    var lastModifyDate: String?
    
    init?() {
        
    }
}

class Content {
    var contentId: String?
    var contentImage: String?
    
    init?() {
        
    }
}
